// tarot.data.js — the full Rider–Waite–Smith deck, all 78 cards.
// Readings are anchored in the Smith/Waite imagery (Pictorial Key to the
// Tarot, 1909 — public domain) and kept in the house's own register: the
// first telling, no imperatives, no clinical voice.
// anim: { kind, words } — the Pixi scene viz.js performs for majors, aces
// and courts. pip cards carry anim:null; viz synthesizes their motion from
// the suit glyph (wands wave, cups fill, swords fall, pentacles spin).
window.LIBER_ARCANA_DATA = window.LIBER_ARCANA_DATA || {};
(function () {
  function C(id, name, n, glyph, up, rev, anim) { return { id: id, name: name, n: n, glyph: glyph, up: up, rev: rev, anim: anim }; }

  var deck = [
    // ── the majors: the heavy roads. each with its own animation. ────────
    C('fool', 'the fool', 0, 'O',
      "a step taken without a map — the pack on the shoulder, the eye on the sky, the cliff not yet mentioned",
      "the step taken to fall: recklessness — or the fool held back from the edge at the last instant",
      { kind: 'fool', words: ['O', '\u263c', '\u2605'] }),
    C('magician', 'the magician', 1, '\u263d',
      "will bent into form — the wand raised, the table laid with everything needed already on it",
      "will with the leash slipped: the trick that serves the trickster, power unused or used poorly",
      { kind: 'magician', words: ['\u263d', '\u221e', '\u2660', '\u2665', '\u2666', '\u2663'] }),
    C('high-priestess', 'the high priestess', 2, '\u26ae',
      "what is hidden, kept — the veil between the pillars, the scroll half-read and half-kept",
      "the secret surfaces, or the listening fails: the veil ignored — or clung to past its season",
      { kind: 'veil', words: ['\u26ae', 'B', 'J', '\u2261'] }),
    C('empress', 'the empress', 3, '\u2640',
      "a body that bears — the garden grown thick, the crown of stars, plenty without asking",
      "the garden grows wild, or the tending smothers: creation blocked, or love that will not let go",
      { kind: 'grow', words: ['\u2640', '\u2698', '\u273f'] }),
    C('emperor', 'the emperor', 4, '\u2642',
      "a line drawn and held — the throne set on stone, the orb and the sceptre, order as shelter",
      "the line grown rigid: the grip gone cold, the wall that keeps nothing out and everything in",
      { kind: 'wall', words: ['\u2642', '\u25a0', '\u25a0'] }),
    C('hierophant', 'the hierophant', 5, '\u263c',
      "the old teaching handed over — the blessing given, the crossed keys, the path worn by others",
      "the teaching hardened into dogma — or the handed-down path refused, and a new one cut",
      { kind: 'keys', words: ['\u26a7', '\u039e'] }),
    C('lovers', 'the lovers', 6, '\u26a5',
      "two become a question — the union blessed from above, the mountain waiting behind it",
      "the union out of tune: values misaligned, a choice deferred, the blessing looked at but not heard",
      { kind: 'union', words: ['\u26a5', '\u2665', '\u2193'] }),
    C('chariot', 'the chariot', 7, '\u2694',
      "force, harnessed — the canopy of stars, the two beasts pulling one way because the driver holds",
      "the reins dropped: direction lost, or force spent on the wrong wall at speed",
      { kind: 'charge', words: ['\u2694', '\u2192', '\u2192'] }),
    C('strength', 'strength', 8, '\u03a9',
      "softness against the throat — the lion's jaw in the patient hand, the infinity above it all",
      "the patience fails: force where gentleness was meant, or the lion met while doubting the hand",
      { kind: 'lion', words: ['\u03a9', '\u221e'] }),
    C('hermit', 'the hermit', 9, '\u2eec',
      "the lamp, the corridor — alone on the peak, the light carried low enough to light one step",
      "the retreat grown total: the lamp kept but no steps taken, or the peak never left",
      { kind: 'hermit', words: ['\u2eec', '\u263c'] }),
    C('wheel-of-fortune', 'wheel of fortune', 10, '\u2638',
      "it turns, indifferent — the sphinx on top this hour, the serpent below; up and down are the same wheel",
      "the turning resisted — or the lucky hour arrived and gone unclaimed",
      { kind: 'wheel', words: ['\u2638', 'T', 'A', 'R', 'O'] }),
    C('justice', 'justice', 11, '\u2696',
      "the weight, returned — the sword up and the scales even; what was measured is measured truly",
      "the scales tipped by a thumb: bias, excuse, the accounting dodged",
      { kind: 'scales', words: ['\u2696', '\u262f'] }),
    C('hanged-man', 'the hanged man', 12, '\u2693',
      "let go, downward — the world turned over on one leg's rope, and the view is better upside down",
      "the hanging that serves nothing: stalling dressed as surrender, the sacrifice no one asked for",
      { kind: 'hang', words: ['\u2693', '\u25cb'] }),
    C('death', 'death', 13, '\u271d',
      "an ending, named — not the skeleton's victory, but the gate it rides through; something will not carry forward",
      "the ending refused: the door held shut until it opens anyway, or opened too soon",
      { kind: 'death', words: ['\u271d', '\u2687'] }),
    C('temperance', 'temperance', 14, '\u2697',
      "two waters, one cup — poured back and forth without spilling, the middle found and held",
      "the pour gone uneven: excess, haste, the blend never tasted",
      { kind: 'pour', words: ['\u2697', '\u2248'] }),
    C('devil', 'the devil', 15, '\u2316',
      "the chain you did not see — loose enough to lift off, worn anyway; the bargain named aloud at last",
      "the chain dropped — or the bargain renewed with better wording",
      { kind: 'chain', words: ['\u2316', '\u2692'] }),
    C('tower', 'the tower', 16, '\u26a1',
      "the structure, broken — the crown blown off, the lightning honest where the masonry was not",
      "the fall almost avoided — or the tower kept standing out of fear of the fall it needs",
      { kind: 'tower', words: ['\u26a1', '\u2317', '\u2593'] }),
    C('star', 'the star', 17, '\u2605',
      "small light, far — the water poured back to the pool, the shore behind, the night navigable",
      "the light dimmed: hope thinned, the pouring stopped — or kept pouring with an empty jug",
      { kind: 'star', words: ['\u2605', '\u2248'] }),
    C('moon', 'the moon', 18, '\u263e',
      "things, in water — the path through the night that is not lying, but is not true either",
      "the fog thins: what seemed real in the dark re-measures in the morning — or the fog is kept for cover",
      { kind: 'moon', words: ['\u263e', '\u2248', '\u2126'] }),
    C('sun', 'the sun', 19, '\u2600',
      "open, burning — everything visible at last, the wall climbed, joy without a shadow to stand in",
      "the light dimmed by cloud: joy qualified, the good hour doubted out of habit",
      { kind: 'sun', words: ['\u2600', '\u273c'] }),
    C('judgement', 'judgement', 20, '\u266a',
      "a sound, far off — the rising answered; what was buried calls itself back by name",
      "the call not answered: the verdict deferred, the rising refused",
      { kind: 'trumpet', words: ['\u266a', '\u2191'] }),
    C('world', 'the world', 21, '\u25cb',
      "a circle, closed — the dance inside the wreath; the whole road walked and the door still open",
      "the circle left open: the last step not taken, the dance ended a bar early",
      { kind: 'world', words: ['\u25cb', '\u2e18'] }),

    // ── wands: fire, the doing ───────────────────────────────────────────
    C('wands-ace', 'ace of wands', 1, '\u2665', "a spark in the hand — the beginning that needs nothing but striking", "the spark smothered, or struck late", { kind: 'spark', words: ['\u2665', '\u2727'] }),
    C('wands-2', 'two of wands', 2, '\u2665\u2665', "the world held in the palm, the other wand fixed to the wall — planning the doing", "the plan doubted, or the map mistaken for the road", null),
    C('wands-3', 'three of wands', 3, '\u2665\u2665\u2665', "ships coming in on the horizon the plan promised — looking outward from what was built", "the ships late, or the horizon misjudged", null),
    C('wands-4', 'four of wands', 4, '\u2665\u2665\u2665\u2665', "the garland strung between four poles — a threshold celebrated, a homecoming", "the homecoming delayed, the bridge not quite finished", null),
    C('wands-5', 'five of wands', 5, '\u2665\u2665\u2665\u2665\u2665', "five sticks, five players, no winner yet — the honest scuffle of competition", "the scuffle turned sour, or the contest avoided", null),
    C('wands-6', 'six of wands', 6, '\u2665\u2665\u2665\u2665\u2665\u2665', "the rider coming home with the wreath — victory that gets seen", "the wreath heavy: recognition wanted too much, or a hollow win", null),
    C('wands-7', 'seven of wands', 7, '\u2665\u2665\u2665\u2665\u2665\u2665\u2665', "the high ground held — one against the slope, and holding", "the ground yielded too early, or held out of stubbornness", null),
    C('wands-8', 'eight of wands', 8, '\u2665\u2665\u2665\u2665\u2665\u2665\u2665\u2665', "eight sticks already flying — speed, messages, everything moving at once", "the flight delayed: messages lost, momentum stalled", null),
    C('wands-9', 'nine of wands', 9, '\u2665\u2665\u2665\u2665\u2665\u2665\u2665\u2665\u2665', "one last stand, bandaged — the reserve left, and it is enough", "the guard kept up past the war's end", null),
    C('wands-10', 'ten of wands', 10, '\u2665\u00d710', "the whole bundle carried to the house — done, and carrying all of it", "the bundle set down late, or carried the wrong direction", null),
    C('wands-page', 'page of wands', 11, '\u2665\u21b3', "the spark studied like a small animal — eagerness before the doing", "the spark chased and dropped", { kind: 'spark', words: ['\u2665', '\u2727'] }),
    C('wands-knight', 'knight of wands', 12, '\u2665\u21a0', "the charge — passion with a horse under it, glorious and unquarantined", "the charge into nothing: energy scattered, promises outrun", { kind: 'charge', words: ['\u2665', '\u2192'] }),
    C('wands-queen', 'queen of wands', 13, '\u2665\u263e', "the fire held warm, not wild — the sunflower, the black cat at ease", "the warmth turned to demand, or the confidence gone hollow", { kind: 'sun', words: ['\u2665'] }),
    C('wands-king', 'king of wands', 14, '\u2665\u263a', "the fire governed — vision made leadable, others warmed by it", "the governance gone to pride: fire used to rule, not to warm", { kind: 'spark', words: ['\u2665', '\u263a'] }),

    // ── cups: water, the feeling ─────────────────────────────────────────
    C('cups-ace', 'ace of cups', 1, '\u2665', "the cup offered, full — feeling at its start, from a hand out of a cloud", "the cup refused, or the feeling poured out with nowhere to go", { kind: 'cup', words: ['\u2665', '\u2248'] }),
    C('cups-2', 'two of cups', 2, '\u2665\u2665', "two cups and a caduceus between them — the meeting that makes a pair", "the pair out of balance: the offer unequally met", null),
    C('cups-3', 'three of cups', 3, '\u2665\u2665\u2665', "three cups raised together — friendship, the harvest danced", "the circle strained, or celebration overdone", null),
    C('cups-4', 'four of cups', 4, '\u2665\u00d74', "the offered cup not seen — bored with what is there, missing what is offered", "the world re-entered: the cup finally seen — or the fog clung to", null),
    C('cups-5', 'five of cups', 5, '\u2665\u00d75', "three spilled, two standing — grief that still has something left in it", "the turn not taken: the standing cups walked past", null),
    C('cups-6', 'six of cups', 6, '\u2665\u00d76', "flowers given in cups, the old yard — memory sweet and uncomplicated", "the past visited too long, or a sweetness that was never as simple", null),
    C('cups-7', 'seven of cups', 7, '\u2665\u00d77', "seven cups in the cloud — every option offered, none of them solid yet", "the choosing done by daydream, or the options already wasted", null),
    C('cups-8', 'eight of cups', 8, '\u2665\u00d78', "eight cups stacked and left standing — walking away from what was good enough", "the walk-away cancelled, or the leaving done in the wrong direction", null),
    C('cups-9', 'nine of cups', 9, '\u2665\u00d79', "the wish card — arms folded, cups arced behind, satisfied", "the satisfaction surface-deep: the wish met but not the want", null),
    C('cups-10', 'ten of cups', 10, '\u2665\u00d710', "the rainbow and the household — contentment complete, on the ground and not in the sky", "the picture tested against the household and found weathered", null),
    C('cups-page', 'page of cups', 11, '\u2665\u21b3', "the fish in the cup — a feeling arriving, odd and sincere", "the feeling mocked or dismissed before it could speak", { kind: 'cup', words: ['\u2665'] }),
    C('cups-knight', 'knight of cups', 12, '\u2665\u21a0', "the offer riding out — romance at a walk, steady and shallow-watered", "the offer all procession: feeling enacted, not held", { kind: 'pour', words: ['\u2665'] }),
    C('cups-queen', 'queen of cups', 13, '\u2665\u263e', "the cup that holds anything — feeling mastered by feeling it, not by closing it", "the depths taken in until they flood: empathy without a shore", { kind: 'cup', words: ['\u2665'] }),
    C('cups-king', 'king of cups', 14, '\u2665\u263a', "calm on the water's surface — feeling ruled so it can be used", "the calm a lid: feeling ruled by force, and leaking anyway", { kind: 'cup', words: ['\u2665'] }),

    // ── swords: air, the thinking ────────────────────────────────────────
    C('swords-ace', 'ace of swords', 1, '\u2660', "the first cut — a thought that clears the air by passing through it", "the blade turned inward, or the clarity weaponised", { kind: 'sword', words: ['\u2660'] }),
    C('swords-2', 'two of swords', 2, '\u2660\u2660', "blindfolded, arms crossed, two blades balanced — the stalemate chosen over the seeing", "the blindfold slipping: the decision can no longer be not-made", null),
    C('swords-3', 'three of swords', 3, '\u2660\u2660\u2660', "the heart pierced by weather — heartbreak, plain, named, survivable", "the blade kept in: the wound rehearsed, or the healing refused", null),
    C('swords-4', 'four of swords', 4, '\u2660\u00d74', "the effigy at rest in the chapel — the blade hung up, the fight paused", "rest refused until the body decides instead — or rest gone on past its use", null),
    C('swords-5', 'five of swords', 5, '\u2660\u00d75', "won, and nothing gained — the hollow victory, the squall after", "the fight left standing: de-escalation, or resentment stored", null),
    C('swords-6', 'six of swords', 6, '\u2660\u00d76', "the ferry to the far shore — moving on quietly, the hard part rowed by someone else", "the passage dodged, or the cargo (what had to be brought) dropped in the water", null),
    C('swords-7', 'seven of swords', 7, '\u2660\u00d77', "five carried, two left — the strategic exit, taken quietly", "the quiet exit caught — or honesty finally carried instead", null),
    C('swords-8', 'eight of swords', 8, '\u2660\u00d78', "bound among eight blades — the constraint real, but the blindfold tied by the bound", "one loop cut: the binding understood as partly self-made", null),
    C('swords-9', 'nine of swords', 9, '\u2660\u00d79', "awake at the bad hour, the nine blades on the wall — the night that makes everything true", "the morning arrives: the dread measured against daylight — or the night clung to for proof", null),
    C('swords-10', 'ten of swords', 10, '\u2660\u00d710', "the worst has happened and it is over — the sky black, the horizon already red", "the ending dragged out, or the falling stopped before the ground and risen from", null),
    C('swords-page', 'page of swords', 11, '\u2660\u21b3', "the lookout — quick eyes, sharper tongue, information before wisdom", "the watch turned to spying, the tongue ahead of the thought", { kind: 'sword', words: ['\u2660'] }),
    C('swords-knight', 'knight of swords', 12, '\u2660\u21a0', "the charge of thought — direct, fast, right past the nuance", "the charge into the argument: right, and wrong-headed", { kind: 'charge', words: ['\u2660', '\u2192'] }),
    C('swords-queen', 'queen of swords', 13, '\u2660\u263e', "the clear seeing that has grieved — perception without sentimentality", "the clear seeing hardened: coldness mistaken for clarity", { kind: 'scales', words: ['\u2660'] }),
    C('swords-king', 'king of swords', 14, '\u2660\u263a', "judgement rendered — thought governed, authority by reason", "the judgement turned tyrannical: reason as a weapon only", { kind: 'sword', words: ['\u2660'] }),

    // ── pentacles: earth, the having ─────────────────────────────────────
    C('pentacles-ace', 'ace of pentacles', 1, '\u2663', "the seed in the palm, offered from the cloud — worth at its start, a garden not yet planted", "the seed gripped too tight to plant, or the offer uncounted", { kind: 'coin', words: ['\u2663'] }),
    C('pentacles-2', 'two of pentacles', 2, '\u2663\u2663', "two coins juggled on the rolling deck — keeping two lives going at once", "the juggling dropped: one life funded at the other's cost", null),
    C('pentacles-3', 'three of pentacles', 3, '\u2663\u2663\u2663', "the craft honoured in the cathedral — skill shown, plans held, work respected", "the craft unvalued, or the collaboration uneven", null),
    C('pentacles-4', 'four of pentacles', 4, '\u2663\u00d74', "the city held at the feet, the heart, the crown — security kept by holding everything", "the grip loosened a little, or tightened past sense", null),
    C('pentacles-5', 'five of pentacles', 5, '\u2663\u00d75', "out in the snow past the lit window — hardship, and the door unknocked", "the window noticed: help asked for at last — or the cold stayed in out of pride", null),
    C('pentacles-6', 'six of pentacles', 6, '\u2663\u00d76', "the scales and the giving hand — generosity measured out, and worth weighing", "the giving uneven, the scales tipped by who holds them", null),
    C('pentacles-7', 'seven of pentacles', 7, '\u2663\u00d77', "the pause, hoe in hand, fruit grown on the vine — patience assessed", "the assessment abandoned, or patience without harvest", null),
    C('pentacles-8', 'eight of pentacles', 8, '\u2663\u00d78', "the bench, the tools, eight coins in a row — work loved for its own repetition", "the work ground down to drudgery, or perfectionism ", null),
    C('pentacles-9', 'nine of pentacles', 9, '\u2663\u00d79', "the vineyard, the falcon hooded, abundance earned alone — self-sufficiency made real", "the abundance kept behind walls: alone, and defended", null),
    C('pentacles-10', 'ten of pentacles', 10, '\u2663\u00d710', "the arch, the dogs, the household through generations — legacy, wealth that outlives its earner", "the legacy argued over, or the long view traded for the short", null),
    C('pentacles-page', 'page of pentacles', 11, '\u2663\u21b3', "the coin studied close — the student of the real, methodical, unhurried", "the study all plan: the coin admired, never used", { kind: 'coin', words: ['\u2663'] }),
    C('pentacles-knight', 'knight of pentacles', 12, '\u2663\u21a0', "the plod — the slowest rider, the only one who arrives", "the plod become stall: routine as a place to hide", { kind: 'charge', words: ['\u2663', '\u2192'] }),
    C('pentacles-queen', 'queen of pentacles', 13, '\u2663\u263e', "the garden fed by the one who runs it — practical nurture, abundance shared", "the nurture bought: worth confused with what it can pay for", { kind: 'grow', words: ['\u2663'] }),
    C('pentacles-king', 'king of pentacles', 14, '\u2663\u263a', "the harvest ruled — worth accumulated and governed, steady as a wall", "the rule gone to hoarding, or the wall defended with it", { kind: 'coin', words: ['\u2663'] })
  ];

  window.LIBER_ARCANA_DATA.tarot = deck;
})();
